server:
  port: 8083

auth:
  keys:
    public-key: TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzS3JlcGM1OWtsdFF3d29PV05KWQppVVlrbjBtYmdhalNSWTdLYWZ0VGpyUVRmTXB4djRDc050RlJKSDI0cnNyVE5yZTJabTdUMVd5UXc2ejhyQmllCm1wdEc2YXQxR0JSdnNWZ2xuV1Zva25tdGovb0JGRGJDSngyK0NZalNrc2dtb2V0eXVCYU80MzdpWldSNUM1THkKZ0RVNzRGNDFwYXZCdnBhdmZVZ1ViMzR6b2E3bC9mcnlYM1REY2JyS3U2dXR4NnVzVFhzMUNvc2twVmJ2MldtRApVdDNTUlNScVlTMGRLblBwRU5DLzNIb0dmQ3dzMGcwL01tVTM3c0FMWHRQcHhRcTM0MTkzTDhuQmFRN1hnOExYCk1ENWxFR1c5NnJESzVrb2JMcVdLLzMraGFHVFZsUmZ6cktST1dSZjkxREd5SFZuVkJLVDNvOXI1QmFNTHV5amwKZVFJREFRQUI=
    private-key: TUlJRGJqQ0NBbGFnQXdJQkFnSUpBSSttWlhoN1VqWm9NQTBHQ1NxR1NJYjNEUUVCQ3dVQU1HVXhDekFKQmdOVgpCQVlUQWxOV01SVXdFd1lEVlFRSUV3eFRZVzRnVTJGc2RtRmtiM0l4RlRBVEJnTlZCQWNUREZOaGJpQlRZV3gyCllXUnZjakVNTUFvR0ExVUVDaE1EVlVSQ01Rd3dDZ1lEVlFRTEV3TlZSRUl4RERBS0JnTlZCQU1UQTFWRVFqQWUKRncweU1UQTVNVFl4TnpNNE1EZGFGdzB5TVRFeU1UVXhOek00TURkYU1HVXhDekFKQmdOVkJBWVRBbE5XTVJVdwpFd1lEVlFRSUV3eFRZVzRnVTJGc2RtRmtiM0l4RlRBVEJnTlZCQWNUREZOaGJpQlRZV3gyWVdSdmNqRU1NQW9HCkExVUVDaE1EVlVSQ01Rd3dDZ1lEVlFRTEV3TlZSRUl4RERBS0JnTlZCQU1UQTFWRVFqQ0NBU0l3RFFZSktvWkkKaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMQ3EzcVhPZlpKYlVNTUtEbGpTV0lsR0pKOUptNEdvMGtXTwp5bW43VTQ2MEUzektjYitBckRiUlVTUjl1SzdLMHphM3RtWnUwOVZza01Pcy9Ld1lucHFiUnVtcmRSZ1ViN0ZZCkpaMWxhSko1clkvNkFSUTJ3aWNkdmdtSTBwTElKcUhyY3JnV2p1Tis0bVZrZVF1UzhvQTFPK0JlTmFXcndiNlcKcjMxSUZHOStNNkd1NWYzNjhsOTB3M0c2eXJ1cnJjZXJyRTE3TlFxTEpLVlc3OWxwZzFMZDBrVWthbUV0SFNwego2UkRRdjl4NkJud3NMTklOUHpKbE4rN0FDMTdUNmNVS3QrTmZkeS9Kd1drTzE0UEMxekErWlJCbHZlcXd5dVpLCkd5Nmxpdjkvb1doazFaVVg4NnlrVGxrWC9kUXhzaDFaMVFTazk2UGErUVdqQzdzbzVYa0NBd0VBQWFNaE1COHcKSFFZRFZSME9CQllFRkdtTkdINVpqa2dHUlRGQVp6Wk53RzJsdFNCNE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUUFaeE9RMVVMSXRoQ2JNcTRITUtDS3NZWDVibGJsQml5UlVzNnRjTmViQWJzZ1NkOGJwYWlmZGpRRGUwYXJjCnRtY1RnOGpMazRuMHcrYzhEdTZnVnNpVGNrckc0WEZJS003UTcrOU02M3FhTzBkY3V6Y2dMaGpQb3ZYbnFNR1gKNUVSV1paYkVweHp4T1NZRjhnbmROQ2JqS2VTNXR5emVFTlUxdGhCOHJEVStFUEN2SmVidXI2RCt3STJTdkprbwpGTUFId1pSS1JtRndrZVMxRWxPNFFVWVJlNWkwZzhPdlVKT2xVeXp6K1F0L0t1ME15YzJPMWgxZVlVM3BycG9pCkJodHRueXJjdVlac2U3YjVPZFVwS0ZVT3kzaHJNbjBIUUhJMVFiSW5DOUhVMkVSTnpaelI5NWtBZHR1c2JyZWwKTnAzN3pYWERyeU51bjZZaEJ4eUVDSGMr
  jwt:
    key: 2r5u8x/A?D(G+KbPeShVkYp3s6v9y$B&E)H@McQfTjWnZq4t7w!z%C*F-JaNdRgU
    duration: 36000000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/oauth/token
logbook:
  format:
    style: http

logging:
  level:
    org.springframework: INFO
    sv.com: DEBUG
    org.zalando.logbook: TRACE