app:
  web-client:
    administration-client:
      remote-address: http://localhost:8085
    back-office:
      remote-address: http://localhost:8082
      user: admin
      pass: admin
      max-attempts: 4
      timeout: 45s
    configuration-client:
      remote-address: http://localhost:8080