version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../documents/YouApp\ Database.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: Password01
    networks:
      - youapp_network
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    networks:
      - youapp_network
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9090:9000"
      - "9091:9001"
    volumes:
      - minio_data:/data
    networks:
      - youapp_network
    command: server /data --console-address ":9001"

networks:
  youapp_network:
    internal: false

volumes:
  mysql_data:
    external: false
  minio_data:
    external: false
